name: secret

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Load secret
        env:
          SECRET_VALUE: ${{ secrets.SECRET }}
        run: echo "Secret configured"

      - name: Safe secret reference
        run: echo "The secret is \${{ secrets.SECRET }}"
